
export component DoubleBarUsageChart inherits Rectangle {
    vertical-stretch: 1;

    in property <[Network-Upload-Download-Data]> vals: [
        { download: 10, upload: 34 },
        { download: 20, upload: 25 },
        { download: 30, upload: 76 },
        { download: 40, upload: 12 },
        { download: 50, upload: 45 },
        { download: 60, upload: 67 }
    ];
    in property <float> max-val: 100;
    in property <string> y-unit: "%";
    property <length> extra-size: 25px;

    HorizontalLayout {
        VerticalLayout {
            // 1st row

            HorizontalLayout {

                HorizontalLayout {
                    Rectangle {
                        width: extra-size;
                        height: extra-size;
                    }
                }

                HorizontalLayout {
                    alignment: space-between;
                    for i in [60, 50, 40, 30, 20, 10, 0]: Rectangle {
                        background: #ffffff71;
                        width: 1px;
                    }
                }

                HorizontalLayout {
                    Rectangle {
                        width: extra-size;
                        height: extra-size;
                    }
                }
            }

            // mid row
        Rectangle {
            //vertical-stretch: 1;
            HorizontalLayout {
                    Rectangle {
                        width: extra-size;
                        VerticalLayout {
                            alignment: space-between;
                            for i in [100, 75, 50, 25, 0]: Rectangle {
                                background: #ffffff71;
                                height: 1px;
                            }
                        }
                    }

                    VerticalLayout {
                        Rectangle {

                            // ---------------------- Chart area --------------------
                        plotting-area := HorizontalLayout {
                                Rectangle {
                                    vertical-stretch: 1;
                                    VerticalLayout {

                                        HorizontalLayout {
                                            alignment: space-between;
                                            for i in [60, 50, 40, 30, 20, 10, 0]: Rectangle {
                                                background: #ffffff71;
                                                width: 1px;
                                            }
                                        }
                                    }

                                    HorizontalLayout {
                                        VerticalLayout {
                                            alignment: space-between;
                                            for i in [100, 75, 50, 25, 0]: Rectangle {
                                                background: #ffffff71;
                                                height: 1px;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    Rectangle {
                        width: extra-size;
                        VerticalLayout {
                            alignment: space-between;
                            for i in [100, 75, 50, 25, 0]: Rectangle {
                                background: #ffffff71;
                                height: 1px;
                            }
                        }
                    }
                }
            }

            // last row
        HorizontalLayout {
                HorizontalLayout {
                    Rectangle {
                        width: extra-size;
                        height: extra-size;
                    }
                }

                HorizontalLayout {
                    alignment: space-between;
                    for i in [60, 50, 40, 30, 20, 10, 0]: Rectangle {
                        background: #ffffff71;
                        width: 1px;
                    }
                }

                HorizontalLayout {
                    Rectangle {
                        width: extra-size;
                        height: extra-size;
                    }
                }
            }

            HorizontalLayout {
                HorizontalLayout {
                    Rectangle {
                        width: extra-size - 5px;
                        height: extra-size;
                    }
                }

                HorizontalLayout {
                    alignment: space-between;
                    for i in ["60s", "50s", "40s", "30s", "20s", "10s", "00s"]: Text {
                        text: i;
                        font-size: 12px;
                    }
                }

                HorizontalLayout {
                    Rectangle {
                        width: extra-size - 5px;
                        height: extra-size;
                    }
                }
            }
        }

        VerticalLayout {
            Rectangle {
                height: extra-size - 5px;
            }

            VerticalLayout {
                alignment: space-between;
                for i in 5: Text {
                    text: max-val * (4 - i) / 4 + y-unit;
                    horizontal-alignment: center;
                    font-size: 12px;
                }
            }

            Rectangle {
                height: extra-size * 2 - 5px;
            }
        }
    }

    // -------------- Plotting ----------------
    Rectangle {
        //background: cyan;
        x: extra-size;
        y: extra-size;
        clip: true;

        height: plotting-area.height;
        width: plotting-area.width;

        HorizontalLayout {
            spacing: 5px;

            for val in 60 - vals.length: VerticalLayout {
                alignment: end;
                Rectangle {
                    background: red;
                    height: 0;
                }
            }

            for val in vals: VerticalLayout {
                alignment: end;
                Rectangle {
                    border-width: 1px;
                    height: 100%;

                    VerticalLayout {
                        alignment: end;
                        Rectangle {
                            //background: #72ffb6;

                            height: (val.download > val.upload ? val.download : val.upload) / max-val * plotting-area.height;
                            border-width: 1px;
                            border-color: #ffffff55;
                        }
                    }

                    Rectangle {
                        height: 5px;
                        background: #72ffb6;
                        y: plotting-area.height - val.download / max-val * plotting-area.height;
                    }

                    Rectangle {
                        height: 5px;
                        background: #ff61a5;
                        y: plotting-area.height - val.upload / max-val * plotting-area.height;
                    }
                }
            }
        }
    }
}
