export component Hero-Header inherits Rectangle {

    in property <string> label: "Label";
    in property <string> additional-text;
    in property <string> header-title: "Header-Title";
    in property <color> font-color: white;
    in property <color> additional-text-color: white;
    in property <color> bar-color: #37ff00;

    vertical-stretch: 0.1;
    VerticalLayout {
        padding: 5px;
        spacing: 5px;
        alignment: end;

        HorizontalLayout {
            alignment: end;

            Text {
                text: label;
                font-size: 80px;
                vertical-alignment: center;
                color: font-color;
            }

            if !additional-text.is-empty: Text {
                text: additional-text;
                vertical-alignment: center;
                font-size: 40px;
                color: additional-text-color;
            }
        }

        Text {
            text: header-title;
            horizontal-alignment: right;
        }
    }
}
