export component PaneButton inherits Rectangle {
    in property <string> title: "NavButton";
    in property <int> id: 0;

    in property <color> bg-color;
    in property <color> hover-color;
    in property <color> press-color;

    callback pressed(int);

    touch := TouchArea {
        clicked => {
            root.pressed(id);
        }
    }

    background: {
        if touch.pressed {
            press-color
        } else if touch.has-hover {
            hover-color
        } else {
            bg-color
        }
    }

    Text {
        font-size: 20px;
        //font-family: "Ubuntu Sans Mono";
        font-weight: 800;
        text: title;
        color: black;
    }
}
