import { PaneButton } from "PaneButton.slint";
export component SideBar inherits Rectangle {
    callback selector(int);

    in property <[{title: string, id: int}]> paneButtons;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        for elements in paneButtons: PaneButton {
            min-height: 40px;
            title: elements.title;
            id: elements.id;
            pressed(id) => {
                root.selector(id);
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }

        PaneButton {
            min-height: 40px;
            title: "Settings";
            id: 11;
            pressed(id) => {
                root.selector(id);
            }
        }
    }
}
