import { CPU-InfoPane } from "Cpu/InfoPane.slint";
import { UsageChart } from "../Widgets/UsageChart.slint";
import { Cpu-Cores } from "Cpu/Cores.slint";
import { Cpu-Full-Data } from "Cpu/DataTypes.slint";
import { Hero-Header } from "../Widgets/Hero-Header.slint";


export component CpuPane inherits Rectangle {

    in property <Cpu-Full-Data> data;

    VerticalLayout {
        spacing: 10px;
        padding: 10px;
        Hero-Header {
            label: data.total-consumption;
            additional-text: "%";
            header-title: "CPU Consumption";
        }

        Rectangle {
            height: 2px;
            background: #ff6a00;
        }

        Rectangle {
            VerticalLayout {
                spacing: 10px;

                Rectangle {
                    border-width: 1px;
                    border-color: white;
                    border-radius: 10px;
                    background: #00000050;
                    VerticalLayout {
                        padding: 10px;
                        UsageChart {
                            vals: data.cpu-consumption.vals;
                            max-val: data.cpu-consumption.max;
                            y-unit: "%";
                        }
                    }
                }

                Rectangle {
                    height: 2px;
                    background: #ff6a00;
                }

                HorizontalLayout {

                    Cpu-Cores {
                        usage_percent: data.core-usage;
                        max-width: 400px;
                    }

                    CPU-InfoPane {
                        min-width: 300px;
                        //max-width: 400px;

                        vertical-stretch: 0;
                        cpu-info: data.cpu-info;
                        processor-info: data.processor-info;
                    }
                }
            }
        }
    }
}
