import { Hero-Header } from "../Widgets/Hero-Header.slint";
import { UsageChart } from "../Widgets/UsageChart.slint";
import { InfoCard } from "../Widgets/Infocard.slint";

export component DiskPane inherits Rectangle {
    VerticalLayout {
        Hero-Header {
            label: "IO";
            header-title: "Disk IO";
        }

        Rectangle {
            HorizontalLayout {
                padding: 5px;
                spacing: 5px;
                Rectangle {

                    VerticalLayout {
                        // Charts Here
                       UsageChart { }

                        // Infocards
                       InfoCard { }
                    }
                }

                Rectangle {
                    width: 2px;
                    background: #37ff00;
                }

                VerticalLayout {
                    alignment: start;
                    InfoCard {
                        max-width: 300px;
                        border-width: 1px;
                        border-radius: 10px;
                        border-color: white;
                        card-data: {
                            card-title: "Nvme01",
                            rows: [
                                { label: "Total", val: "16" },
                                { label: "Available", val: "16" },
                                { label: "Used", val: "16" },
                                { label: "Read", val: "16" },
                                { label: "Write", val: "16" },
                            ]
                        };
                    }
                }
            }
        }
    }
}
