import { QuickMetrics } from "Home/QuickMetrics.slint";
import { InfoRowModel, MetricModel } from "../ModelTypes.slint";
import { BarChart } from "Home/BarChart.slint";
import {
    Home-Metrics-Data,
    Home-StaticInfo-Left-Data,
    Home-StaticInfo-Right-Data,
} from "Home/DataTypes.slint";
import { InfoCard } from "../Widgets/Infocard.slint";
import { Hero-Header } from "../Widgets/Hero-Header.slint";

export component HomePane inherits Rectangle {

    in property <Home-Metrics-Data> metricData;
    in property <Home-StaticInfo-Left-Data> leftInfoPanel;
    in property <Home-StaticInfo-Right-Data> rightInfoPanel;
    in property <[float]> chart-data;

    VerticalLayout {
        Rectangle {
            Hero-Header {
                label: "Excellent";
                header-title: "Overall Health";
            }
        }

        HorizontalLayout {
        // Left Content area
        //alignment: space-between;
        Rectangle {
                horizontal-stretch: 1;

                border-color: #ff7700;
                border-width: 1px;

                VerticalLayout {
                    alignment: end;
                    padding: 10px;
                    spacing: 10px;

                    Rectangle {
                        HorizontalLayout {
                            alignment: start;
                            spacing: 10px;

                            InfoCard {
                                border-width: 1px;
                                border-radius: 10px;
                                border-color: #3cff00;
                                background: #3cff0014;

                                bar-color: #3cff00;
                                card-data: {
                                    card-title: "Oerating System Info",
                                    rows : [
                                        { label: "Hostname : ", val: leftInfoPanel.hostname },
                                        { label: "OS : ", val: leftInfoPanel.os },
                                        { label: "Kernel : ", val: leftInfoPanel.kernel },
                                        { label: "CPU Name : ", val: leftInfoPanel.cpu-name },
                                        { label: "GPU Model : ", val: leftInfoPanel.gpu-model },
                                        { label: "Total RAM : ", val: leftInfoPanel.total-ram },
                                        { label: "Motherboard : ", val: leftInfoPanel.Motherboard },
                                    ]
                                };
                            }

                            Rectangle { }

                            InfoCard {
                                border-width: 1px;
                                border-radius: 10px;
                                border-color: #5ea4ff;
                                background: #5ea4ff16;

                                bar-color: #5ea4ff;
                                card-data: {
                                    card-title: "Stats",
                                    rows : [
                                        { label: "Uptime : ", val: rightInfoPanel.uptime },
                                        { label: "Boot-Time : ", val: rightInfoPanel.boot-time },
                                        { label: "Active Proc : ", val: rightInfoPanel.proc-count },
                                        { label: "Local-IP : ", val: rightInfoPanel.local-ip },
                                    ]
                                };
                            }
                        }
                    }

                    VerticalLayout {
                        spacing: 5px;
                        Text {
                            text: "Memory Usage";
                            font-size: 16px;
                            horizontal-alignment: right;
                        }

                        Rectangle {
                            height: 2px;
                            background: #5ea4ff;
                        }

                        BarChart {
                            height: 250px;

                            border-width: 1px;
                            border-color: #00bfff;
                            border-radius: 10px;

                            vals: chart-data;
                        }
                    }
                }
            }

            // Right Content area
        QuickMetrics {
                border-color: #ff7700;
                border-width: 1px;

                max-width: 400px;
                min-width: 360px;
                horizontal-stretch: 0.3;

                data: metricData;
            }
        }
    }
}
