import { QuickMetrics } from "Home/QuickMetrics.slint";
import { InfoRowModel, MetricModel } from "../ModelTypes.slint";
import { BarChart } from "Home/BarChart.slint";
import {
    Home-Metrics-Data,
    Home-StaticInfo-Left-Data,
    Home-StaticInfo-Right-Data,
} from "Home/DataTypes.slint";
import { InfoCard } from "../Widgets/Infocard.slint";
import { Hero-Header } from "../Widgets/Hero-Header.slint";
import { UsageChart } from "../Widgets/UsageChart.slint";
import { VerticalBox } from "std-widgets.slint";

export component HomePane inherits Rectangle {

    in property <Home-Metrics-Data> metricData;
    in property <Home-StaticInfo-Left-Data> leftInfoPanel;
    in property <Home-StaticInfo-Right-Data> rightInfoPanel;
    in property <{max: float, vals: [float]}> cpu-usage;
    in property <{max: float, vals: [float]}> memory-usage;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        Hero-Header {
            label: "SysInfo";
            header-title: "Monitor System Usage";
        }

        Rectangle {
            height: 2px;
            background: #ff6a00;
        }

        HorizontalLayout {
            spacing: 10px;
        // Left Content area
            Rectangle {
                horizontal-stretch: 1;

                VerticalLayout {
                    spacing: 10px;

                    Rectangle {
                        vertical-stretch: 0;
                        HorizontalLayout {
                            alignment: start;
                            spacing: 10px;

                            InfoCard {
                                border-width: 1px;
                                border-radius: 10px;
                                border-color: #3cff00;

                                drop-shadow-blur: 10px;
                                card-data: {
                                    card-title: "OS Info",
                                    rows : [
                                        { label: "Hostname : ", val: leftInfoPanel.hostname },
                                        { label: "OS : ", val: leftInfoPanel.os },
                                        { label: "Kernel : ", val: leftInfoPanel.kernel },
                                        { label: "CPU Name : ", val: leftInfoPanel.cpu-name },
                                        { label: "GPU Model : ", val: leftInfoPanel.gpu-model },
                                        { label: "Total RAM : ", val: leftInfoPanel.total-ram },
                                        { label: "Motherboard : ", val: leftInfoPanel.Motherboard },
                                    ]
                                };
                            }

                            InfoCard {
                                border-width: 1px;
                                border-radius: 10px;
                                border-color: #5ea4ff;

                                card-data: {
                                    card-title: "Stats",
                                    rows : [
                                        { label: "Uptime : ", val: rightInfoPanel.uptime },
                                        { label: "Boot-Time : ", val: rightInfoPanel.boot-time + " s" },
                                        { label: "Active Proc : ", val: rightInfoPanel.proc-count },
                                        { label: "Local-IP : ", val: rightInfoPanel.local-ip },
                                    ]
                                };
                            }
                        }
                    }

                    Rectangle {
                        height: 2px;
                        background: #ff6a00;
                    }

                    Rectangle {
                        HorizontalLayout {
                            spacing: 10px;

                            Rectangle {
                                border-width: 1px;
                                border-color: white;
                                border-radius: 10px;
                                background: #00000050;
                                VerticalLayout {
                                    spacing: 10px;
                                    padding: 10px;

                                    Rectangle {
                                        Text {
                                            width: 100%;
                                            text: "CPU";
                                            horizontal-alignment: right;
                                        }
                                    }

                                    Rectangle {
                                        height: 2px;
                                        background: #65f0ff;
                                    }

                                    UsageChart {
                                        vals: cpu-usage.vals;
                                        max-val: 100;
                                        y-unit: "%";
                                    }
                                }
                            }

                            Rectangle {
                                border-width: 1px;
                                border-color: white;
                                border-radius: 10px;
                                background: #00000050;
                                VerticalLayout {
                                    spacing: 10px;
                                    padding: 10px;

                                    Rectangle {
                                        Text {
                                            width: 100%;
                                            text: "Memory";
                                            horizontal-alignment: right;
                                        }
                                    }

                                    Rectangle {
                                        height: 2px;
                                        background: #65f0ff;
                                    }

                                    UsageChart {
                                        vals: memory-usage.vals;
                                        max-val: 100;
                                        y-unit: "%";

                                        background: #00000050;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            Rectangle {
                width: 2px;
                background: #ff6a00;
            }

            // Right Content area
        QuickMetrics {
                max-width: 400px;
                min-width: 360px;
                horizontal-stretch: 0.3;

                data: metricData;
            }
        }
    }
}
