export component DiskIO inherits Rectangle {
    vertical-stretch: 1;
    property <length> extra-size: 25px;
    in property <string> y-unit: "KB/s";
    in property <[float]> read-vals: [10, 12, 16, 23, 4, 21];
    in property <[float]> write-vals: [21, 23, 10, 9, 4, 15];
    in property <float> max-val: 23;

    // Main background drawing of graph axis lines and textual labels
    HorizontalLayout {
        VerticalLayout {
            // Top-Extra ticks aligning with internal grid
            HorizontalLayout {
                // Top-Left corner extra area
                Rectangle {
                    width: extra-size;
                    height: extra-size;
                }

                // Ticks on top side of plotting area
                HorizontalLayout {
                    alignment: space-between;
                    // 7 divisons for each X-10sec gap
                    for i in 7: Rectangle {
                        background: #ffffff71;
                        width: 1px;
                    }
                }

                // Top-right corner extra area
                Rectangle {
                    width: extra-size;
                    height: extra-size;
                }
            }

            // Area with Left and right ticks aligned with graph + plotting area
            Rectangle {
                //vertical-stretch: 1;
                HorizontalLayout {
                    // Left graph ticks aligned with internal grid lines
                    Rectangle {
                        width: extra-size;
                        VerticalLayout {
                            alignment: space-between;
                                // 5 division gap for Y-axis
                                for i in 5: Rectangle {
                                background: #ffffff71;
                                height: 1px;
                            }
                        }
                    }

                    // Main Plotting area with graph lines
                    VerticalLayout {
                        // ---------------------- Grid overlays area --------------------
                        plotting-area := Rectangle {
                            vertical-stretch: 1;
                            HorizontalLayout {
                                alignment: space-between;
                                // 7 division gap for X-axis graph background lines
                                for i in 7: Rectangle {
                                    background: #ffffff71;
                                    width: 1px;
                                }
                            }

                            VerticalLayout {
                                alignment: space-between;
                                // 5 divisons gap for Y-axis background graph lines
                                for i in 5: Rectangle {
                                    background: #ffffff71;
                                    height: 1px;
                                }
                            }
                        }
                    }

                    // Right side graph ticks
                    Rectangle {
                        width: extra-size;
                        VerticalLayout {
                            alignment: space-between;
                            for i in [100, 75, 50, 25, 0]: Rectangle {
                                background: #ffffff71;
                                height: 1px;
                            }
                        }
                    }
                }
            }

            // Bottom side graph ticks
            HorizontalLayout {
                // Bottom-left extra corner space
                Rectangle {
                    width: extra-size;
                    height: extra-size;
                }
                
                //Bottom side ticks
                HorizontalLayout {
                    alignment: space-between;
                    for i in [60, 50, 40, 30, 20, 10, 0]: Rectangle {
                        background: #ffffff71;
                        width: 1px;
                    }
                }

                // Bottom-right extra corner space
                Rectangle {
                    width: extra-size;
                    height: extra-size;
                }
            }

            // Bottom side labels
            HorizontalLayout {
                Rectangle {
                    width: extra-size - 5px;
                    height: extra-size;
                }

                HorizontalLayout {
                    alignment: space-between;
                    for i in ["60", "50", "40", "30", "20", "10", "00"]: Text {
                        text: i + "s";
                        font-size: 12px;
                    }
                }

                Rectangle {
                    width: extra-size - 5px;
                    height: extra-size;
                }
            }
        }

        // Horizontal side labels
        VerticalLayout {
            Rectangle {
                height: extra-size - 5px;
            }

            VerticalLayout {
                alignment: space-between;
                for i in 5: Text {
                    text: ((5 - i) * max-val / 5) + " " + y-unit;
                    horizontal-alignment: center;
                    font-size: 12px;
                }
            }

            Rectangle {
                height: extra-size * 2 - 5px;
            }
        }
    }

    // -------------- Plotting ----------------
    read := Rectangle {
        //background: cyan;
        x: extra-size;
        y: extra-size;
        clip: true;

        height: plotting-area.height;
        width: plotting-area.width;

        HorizontalLayout {
            spacing: 5px;

            for val in 60 - read-vals.length: VerticalLayout {
                alignment: end;
                Rectangle {
                    background: red;
                    height: 0;
                }
            }

            for val in read-vals: VerticalLayout {
                alignment: end;
                Rectangle {
                    background: #ff5e5e78;

                    // border-color: {
                    //     if val <= 50 {
                    //         return #00ff22;
                    //     } else if val <= 75 {
                    //         return #ffe100;
                    //     } else {
                    //         return #ff0000;
                    //     }
                    // }
                    border-width: 1px;
                    //border-radius: 10px;

                    height: plotting-area.height * val / max-val; //- 10px;
                }
            }
        }
    }

    write := Rectangle {
        //background: cyan;
        x: extra-size;
        y: extra-size;
        clip: true;

        height: plotting-area.height;
        width: plotting-area.width;

        HorizontalLayout {
            spacing: 5px;

            for val in 60 - write-vals.length: VerticalLayout {
                alignment: end;
                Rectangle {
                    background: red;
                    height: 0;
                }
            }

            for val in write-vals: VerticalLayout {
                alignment: end;
                Rectangle {
                    background: #f200ff5e;

                    // border-color: {
                    //     if val <= 50 {
                    //         return #00ff22;
                    //     } else if val <= 75 {
                    //         return #ffe100;
                    //     } else {
                    //         return #ff0000;
                    //     }
                    // }
                    border-width: 1px;
                    //border-radius: 10px;

                    height: plotting-area.height * val / max-val; //- 10px;
                }
            }
        }
    }
}
