import { SideBar } from "Widgets/Sidebar.slint";
import { TabModel, MetricModel } from "ModelTypes.slint";
import { HomePane } from "TabPanes/Home.slint";
import { CpuPane } from "TabPanes/CPU.slint";
import { Home-Full-Data } from "TabPanes/Home/DataTypes.slint";
import { Cpu-Full-Data } from "TabPanes/Cpu/DataTypes.slint";
import { Memory-Full-Data } from "TabPanes/Memory/DataTypes.slint";
import { MemoryPane } from "TabPanes/Memory.slint";
import { DiskPane } from "TabPanes/Disk.slint";
import { NetworkPane } from "TabPanes/Network.slint";
import { ProcessPane } from "TabPanes/Process.slint";
import { Network-Full-Data } from "TabPanes/Network/DataTypes.slint";


export component TabLayout inherits Rectangle {
    property <int> selected: 0;
    in property <[{title: string, id: int}]> model;

    in property <Home-Full-Data> homeData;
    in property <Cpu-Full-Data> cpu-data;
    in property <Memory-Full-Data> memory-data;
    in property <Network-Full-Data> network-data;
    in property <[[StandardListViewItem]]> process-data;

    HorizontalLayout {
        SideBar {
            min-width: 160px;
            background: #00000050;
            paneButtons: root.model;

            selector(paneId) => {
                selected = paneId;
            }
        }

        Rectangle {
            width: 2px;
            background: #ff6a00;
        }

        Rectangle {
            if selected == 0: HomePane {
                metricData: homeData.metric;
                leftInfoPanel: homeData.leftInfoPanel;
                rightInfoPanel: homeData.rightInfoPanel;
                cpu-usage: cpu-data.cpu-consumption;
                memory-usage: memory-data.memory-usage;
            }

            if selected == 1: CpuPane {
                data: cpu-data;
            }

            if selected == 2: MemoryPane {
                data: memory-data;
            }

            if selected == 3: NetworkPane {
                data: network-data;
            }

            if selected == 4: ProcessPane {
                table-data: process-data;
            }

            if selected > 10: Text {
                text: "Unimplemented!!!";
                color: #ff7474;
            }
        }
    }
}
